spring:
 application:
  name: gateway
 cloud:
  gateway:
   routes:
    - id: security
      uri: http://localhost:6464
      predicates:
        - Path= /security/**
      filters:
       - AuthenticationFilter

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka

            
