spring:
 application:
  name: gateway
 cloud:
  gateway:
   routes:
    - id: UserAuth
      uri: http://localhost:9890
      predicates:
        - Path= /security/**
      filters:
       - AuthenticationFilter
    - id: productmanagement
      uri: http://localhost:8081
      predicates:
        - Path=/api/v1/inventory/**
      filters:
        - AuthenticationFilter



eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka

            
